# Generated by Django 4.2.6 on 2023-12-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
