# Generated by Django 4.2.6 on 2023-11-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_image', models.ImageField(default='not found', upload_to='product/category')),
            ],
        ),
        migrations.CreateModel(
            name='global_productes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_description', models.TextField()),
                ('weight_type', models.CharField(choices=[('kg', 'Kilogram'), ('count', 'Count')], max_length=20)),
                ('prodect_image', models.ImageField(upload_to='product/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prodect.category')),
            ],
        ),
    ]
