# Generated by Django 4.2.6 on 2023-12-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_productes',
            name='weight_type',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('count', 'Count')], max_length=20),
        ),
    ]
