# Generated by Django 4.2.6 on 2023-12-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_products',
            name='offer_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller_products',
            name='offer_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
