# Generated by Django 4.2.6 on 2023-12-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_order_code_alter_order_shop_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ob_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
