# Generated by Django 4.2.6 on 2023-12-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_orderproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='count_type',
            field=models.CharField(default='kg', max_length=5),
        ),
    ]
