# Generated by Django 4.2.6 on 2023-12-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_shop_password'),
        ('seller', '0009_orderproducts_count_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ob_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(default='undifaind', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.shop'),
        ),
    ]
