# Generated by Django 4.2.6 on 2023-12-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_shop_password'),
        ('seller', '0009_orderproducts_count_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ob_id',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='seller.seller_products'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.shop'),
        ),
    ]
