# Generated by Django 4.2.6 on 2023-12-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_shop_password'),
        ('seller', '0010_remove_order_ob_id_remove_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.shop'),
        ),
    ]
