# Generated by Django 4.2.6 on 2023-12-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_alter_order_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ob_id',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='seller.seller_products'),
        ),
    ]
