# Generated by Django 4.2.6 on 2023-12-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_orderproducts_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Billed', 'Billed'), ('Cart', 'Cart'), ('Ordered', 'Ordered'), ('Accepted', 'Accepted'), ('Returned', 'Returned'), ('Canceled', 'Canceled'), ('Paid', 'Paid'), ('Delivered', 'Delivered')], max_length=20),
        ),
    ]
