# Generated by Django 4.2.6 on 2023-12-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
