# Generated by Django 4.2.6 on 2023-12-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0019_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='replaced',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='returned',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5),
        ),
    ]
