# Generated by Django 4.2.6 on 2023-12-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0020_orderproducts_replaced_orderproducts_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='replaced',
        ),
    ]
