# Generated by Django 4.2.6 on 2023-12-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0021_remove_orderproducts_replaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='returned',
            field=models.BooleanField(default=False, max_length=5),
        ),
    ]
