# Generated by Django 4.2.6 on 2023-12-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0023_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Razorpay', 'Razorpay'), ('Cash on Delivery', 'Cash on Delivery')], max_length=20),
        ),
    ]
