# Generated by Django 4.2.6 on 2023-12-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0024_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Billed', 'Billed'), ('Cart', 'Cart'), ('Ordered', 'Ordered'), ('Accepted', 'Accepted'), ('Reordered', 'Reordered'), ('Returned', 'Returned'), ('Replace', 'Replace'), ('Canceled', 'Canceled'), ('Paid', 'Paid'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
