# Generated by Django 4.2.6 on 2024-01-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0025_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_products',
            name='price',
            field=models.FloatField(),
        ),
    ]
