# Generated by Django 4.2.6 on 2024-01-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0026_alter_seller_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
