# Generated by Django 4.2.6 on 2024-01-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0027_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_products',
            name='offer_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
