# Generated by Django 4.2.6 on 2024-01-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0028_alter_seller_products_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
