# Generated by Django 4.2.6 on 2023-11-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shop_banner_image_shop_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_place',
            field=models.CharField(default='not found', max_length=200),
        ),
    ]
