# Generated by Django 4.2.6 on 2023-11-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_shop_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='password',
            field=models.CharField(default='1234', max_length=10),
        ),
    ]
