# Generated by Django 4.2.6 on 2023-12-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_shop_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
